"""Add checklist tables

Revision ID: 8d80e0f9adce
Revises: 1c7c2c939238
Create Date: 2026-03-01 14:56:33.966894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d80e0f9adce'
down_revision: Union[str, Sequence[str], None] = '1c7c2c939238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trades_uuid_key'), 'trades', type_='unique')
    op.drop_column('trades', 'updated_at')
    op.drop_column('trades', 'mae')
    op.drop_column('trades', 'uuid')
    op.drop_column('trades', 'mfe')
    op.drop_column('trades', 'rule_violations')
    op.drop_column('trades', 'exit_slippage')
    op.drop_column('trades', 'entry_slippage')
    op.drop_column('trades', 'emotional_state')
    op.drop_column('trades', 'discipline_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('discipline_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('emotional_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('entry_slippage', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('exit_slippage', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('rule_violations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('mfe', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('mae', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('trades_uuid_key'), 'trades', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
